import assert from 'node:assert/strict';
import test from 'node:test';
import { commandsFromHelp, docsArgs, platformRows, renderCli, renderPlatform, USAGE } from '../scripts/docs.mjs';

const HELP = `Usage: jevris <command> [options]

Public commands (also available as skills and MCP tools inside your coding harness):
  status       Mode, sidecar state
  verify       Run declared checks

Administration:
  install      Install Jevris
  data delete  Delete Jevris data on this machine
  policy, kill-switch, gates   Operator tools; see jevris help <command>

Global options:
  --home <dir>   Jevris home
  -h, --help     Show help`;

test('the CLI page lists every command the help names, including operator tools (UDOC-08)', () => {
  assert.deepEqual(commandsFromHelp(HELP), ['status', 'verify', 'install', 'data delete', 'policy', 'kill-switch', 'gates']);
  // A data row also gets a data delete section: that subcommand has its own help and flags.
  assert.deepEqual(commandsFromHelp('Administration:\n  data         purge | delete\n  pack         list'), ['data', 'data delete', 'pack']);
  const page = renderCli({ help: HELP, version: '1.2.0', commands: [{ name: 'gates', text: 'Usage: jevris gates' }] });
  assert.match(page, /^# CLI reference/);
  assert.match(page, /Generated by scripts\/docs\.mjs/);
  assert.match(page, /## jevris gates\n\n```text\nUsage: jevris gates\n```/);
  assert.match(page, /npx @webventures\/jevris/);
  assert.doesNotMatch(page, /npx jevris /);
});

test('docs.mjs prints its usage on --help and refuses an unknown argument, writing nothing', () => {
  assert.deepEqual(docsArgs(['--help']), { help: true });
  assert.deepEqual(docsArgs(['cli', '-h']), { help: true });
  assert.match(USAGE, /^Usage: node scripts\/docs\.mjs /);
  assert.deepEqual(docsArgs(['--bogus']), { error: 'unknown argument: --bogus' });
  assert.deepEqual(docsArgs(['nope']), { error: 'unknown argument: nope' });
  assert.deepEqual(docsArgs(['--evidence']), { error: '--evidence needs a directory' });
  assert.deepEqual(docsArgs([]), { check: false, evidence: undefined, pages: ['cli', 'platform'] });
  assert.deepEqual(docsArgs(['platform', '--evidence', 'ev', '--check']), { check: true, evidence: 'ev', pages: ['platform'] });
});

const matrix = { node: '^22.14.0 || >=23.6.0', architectures: ['x64', 'arm64'], advertised: [{ harness: 'claude', os: ['darwin', 'win32'] }] };
const cert = (id, os, certifiedAt) => ({
  id,
  kind: 'certification-record',
  payload: {
    harness: 'claude',
    operatingSystems: os,
    harnessVersionRange: { minimum: '2.1.0', maximumExclusive: '2.2.0' },
    certifiedAt,
    expiresAt: '2026-12-31T00:00:00Z',
    features: [{ featureId: 'context', status: 'certified' }, { featureId: 'route', status: 'unsupported' }],
  },
});

test('the platform page shows certified only for records the gates accept (UDOC-10)', () => {
  const records = [cert('old', ['darwin'], '2026-08-01T00:00:00Z'), cert('new', ['darwin'], '2026-09-01T00:00:00Z'), cert('bad', ['win32'], '2026-09-01T00:00:00Z')];
  const rows = platformRows(matrix, records, (r) => (r.id === 'bad' ? 'CERTIFICATION_EXPIRED' : null));
  assert.deepEqual(rows.map((r) => [r.os, r.status]), [['darwin', 'certified'], ['win32', 'not certified']]);
  assert.match(rows[0].detail, /certified 2026-09-01/);
  assert.match(rows[0].detail, /features: context$/);
  assert.match(rows[1].detail, /CERTIFICATION_EXPIRED/);
  const page = renderPlatform({ matrix, rows });
  assert.match(page, /1 of 2 advertised combinations/);
  assert.match(page, /\| claude \| macOS \| certified \|/);
  assert.match(page, /\| claude \| Windows \| not certified \|/);
  assert.match(page, /`\^22\.14\.0 \|\| >=23\.6\.0`/);
});

test('with no records nothing is advertised as certified (UDOC-10)', () => {
  const rows = platformRows(matrix, [], () => null);
  assert.ok(rows.every((r) => r.status === 'not certified' && r.detail === 'no certification record'));
});
