export { explicitClientConfig } from './explicit-client.js';
export { DEFAULT_MAX_RESPONSE_BYTES, SdkTransport, createSdkTransport, retryAfterFrom, statusFailure } from './sdk-transport.js';
export type { FetchLike, SdkTransportOptions } from './sdk-transport.js';
export { NativeReferenceTransport, createNativeReferenceTransport } from './native-transport.js';
export type { NativeTransportOptions } from './native-transport.js';
export { CONFORMANCE_SCENARIOS, MOCK_MODEL, createMockFetch } from './conformance-mock.js';
export type { ConformanceScenario, MockFetch, MockFetchOptions } from './conformance-mock.js';
export { CONFORMANCE_CASES, CONFORMANCE_REQUEST, runConformance, summarize } from './conformance.js';
export type { ConformanceExpectation, ConformanceOutcome } from './conformance.js';
export { GATEWAYS, GATEWAY_IDS, GatewayTransport, createGatewayTransport, normalizeGatewayAnswers } from './gateway.js';
export type { GatewayDescriptor, GatewayId, GatewayInvoke, GatewayRawResult, NormalizeResult } from './gateway.js';
export { LIVE_SUITE_SCHEMA, runLiveSuite } from './live-suite.js';
export type { LatencySample, LiveSuiteOptions, LiveSuiteRecord } from './live-suite.js';
export { DEFAULT_DECISION_BUDGET_MICRO_USD, RULES_ONLY_DIAGNOSTIC, createSidecarEngine } from './sidecar-engine.js';
export { warmDecisionPath } from './warm-up.js';
export type { SidecarEngineOptions } from './sidecar-engine.js';
export { ROUTE_TURN_SPEC, createRouteTurnOp, turnMainSessionOf, turnRequest, turnSessionLinkOf } from './route-turn-op.js';
export type { TurnContext, TurnMainSession } from './route-turn-op.js';
export { engineOf, explainPayload, sessionModelsFrom, sidecarEventSubscribers, sidecarOps, unknownRouteSlices, workerModelOf } from './sidecar-ops.js';
export type { SessionModels } from './sidecar-ops.js';
export { ADVICE_REPEAT_LIMIT, adviceIgnored, openAdvice } from './advice-adherence.js';
export { CONTEXT_FEATURE, ROUTE_FEATURE, cliCertificationSource, createDecisionSubscriber, featureFor, isCertified, recordsCertificationSource } from './sidecar-subscribers.js';
export type { CertificationAnswer, CertificationSource, HookProposal, SubscriberOptions, SubscriberResult, TriggerHandler, TriggerHandlerInput } from './sidecar-subscribers.js';
export { DEFAULT_TRIGGER_HANDLERS, evidenceAdvice, modelChangeAdvice, modelChangeAdviceWith, subagentRouteAdvice, type ModelChangeAdviceDeps } from './trigger-handlers.js';
export { SCOPE_CHANGE_SPEC_ID, createScopeChangeHandler, scopeAskGate, scopeChangeAdvice, scopeReasonCodes } from './scope-handler.js';
export { recordAdviceRun } from './advice-record.js';
export { TEST_PROVIDER_KEY_ENV, TEST_PROVIDER_URL_ENV, providerOverrideDiagnostic, readProviderOverride } from './provider-override.js';
export type { ProviderOverride, ProviderOverrideRefusal } from './provider-override.js';
export { TEST_BUNDLED_CALIBRATION_ENV, TEST_CALIBRATION_KEYS_ENV, bundledCalibrationPath, calibrationKeysOverride, trustedCalibrationKeys, type CalibrationKeysOverride } from './calibration-trust.js';
export { DEFAULT_MAX_REPAIR_ATTEMPTS, FAILURE_ARTIFACT_TEXT, FAILURE_MIN_CONFIDENCE, REPEATED_FAILURE_SPEC_ID, adviseRepeatedFailure, failureAdviceText, failureAskGate, failureContextOf, failureFacts, failureQuestions, parseFailureFeatures, planFailureAdvice } from './failure-advice.js';
export type { FailureAdvice, FailureContext, FailureFeatures, FailurePlan, FailureStep } from './failure-advice.js';
export { BUILT_IN_TEMPLATES, NEW_TASK_SPEC_ID, OPEN_KINDS, OPEN_POINTS, TASK_FAMILIES, TASK_FAMILY_TEXT, adviseNewTask, newTaskAdviceText, newTaskAskGate } from './new-task-advice.js';
export type { NewTaskAdvice, OpenKind, TaskFamily } from './new-task-advice.js';
export { createNewTaskHandler, createRepeatedFailureHandler, newTaskAdvice, repeatedFailureAdvice } from './live-handlers.js';
export type { LiveHandlerOptions } from './live-handlers.js';
export { PENDING_ADVICE, PendingAdviceStore } from './pending-advice.js';
export type { PendingAdvice, PendingKind } from './pending-advice.js';
export { createCallMeter, distributionOf, percentileOf, spentRecord } from './features-meter.js';
export type { AnswerStat, CallMeter, Distribution, ExchangeObserver, MeterLimits, MeterRow, MeterTotals } from './features-meter.js';
export { ENGINE_GROUPS, FAKE_SECRET, FAILURE_CASES, FAILURE_NO_REQUEST_IDS, FEATURE_SUITE_SCHEMA, RANK_SHAPES, SLICE_SHAPES, TASK_PROMPTS, answerDistributions, engineCases, runFeatureSuite, suiteFailures, summarizeGroup } from './features-suite.js';
export type { CaseDef, CaseOutcome, EngineGroup, FeatureRow, FeatureSuiteOptions, FeatureSuiteRecord, GroupSummary, RowPhase } from './features-suite.js';
export { IDLE_SOCKET_MS, MAX_SOCKETS, SPARE_SOCKET_MS, closePrewarmed, nodeFetch, prewarmConnection, prewarmedConnections } from './node-fetch.js';
export { RECORD_STRING_PATHS, recordViolations } from './features-record.js';
export type { RecordCheckOptions } from './features-record.js';
export { FEATURE_INVENTORY, OP_ONLY_ENTRY, inventoryByWiring } from './features-inventory.js';
export type { InventoryEntry, InventoryWiring } from './features-inventory.js';
