/**
 * Serving-host tariffs (serving-hosts design 6.1, R38). Generated by
 * packages/evals/scripts/refresh-serving-tariffs.mjs from a local models.dev snapshot; do not edit by hand.
 * models.dev commit b960b41db3f36c41b56a1d90b712f2a859275107, api.json ETag "2075e967b8882121cafb38297f56987d", read 2026-09-28.
 */
import type { Serving } from '@jevris/contracts';

export const SERVINGS_SNAPSHOT_ON = "2026-09-28";

/** Where each serving source id was read. */
export const SERVING_SOURCES: Readonly<Record<string, { readonly url: string; readonly fetchedOn: string }>> = Object.freeze({
  "MODELSDEV-2075e967": {
    "url": "https://models.dev/api.json",
    "fetchedOn": "2026-09-28"
  },
  "KGW-2026-09-28": {
    "url": "https://api.kilo.ai/api/openrouter/models",
    "fetchedOn": "2026-09-28"
  }
});

export const BUNDLED_SERVINGS: readonly Serving[] = Object.freeze([
  {
    "host": "kilo",
    "provider": "anthropic",
    "modelId": "claude-fable-5-1",
    "hostModelId": "anthropic/claude-fable-5.1",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 10,
      "outputPerMillion": 50,
      "cacheReadPerMillion": 0.25,
      "cacheWritePerMillion": 12.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 10000000,
      "outputMicroUsdPerMillion": 50000000,
      "cacheReadMicroUsdPerMillion": 250000,
      "cacheWriteMicroUsdPerMillion": 12500000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "anthropic",
    "modelId": "claude-opus-5",
    "hostModelId": "anthropic/claude-opus-5",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 5,
      "outputPerMillion": 25,
      "cacheReadPerMillion": 0.5,
      "cacheWritePerMillion": 6.25,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 5000000,
      "outputMicroUsdPerMillion": 25000000,
      "cacheReadMicroUsdPerMillion": 500000,
      "cacheWriteMicroUsdPerMillion": 6250000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "anthropic",
    "modelId": "claude-opus-5-5",
    "hostModelId": "anthropic/claude-opus-5.5",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 4,
      "outputPerMillion": 20,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 4000000,
      "outputMicroUsdPerMillion": 20000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 5000000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "anthropic",
    "modelId": "claude-sonnet-5",
    "hostModelId": "anthropic/claude-sonnet-5",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 10,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 2.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 10000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 2500000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "deepseek",
    "modelId": "deepseek-v4-pro",
    "hostModelId": "deepseek/deepseek-v4-pro",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 1.6,
      "outputPerMillion": 3.2,
      "cacheReadPerMillion": 0.135,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 1600000,
      "outputMicroUsdPerMillion": 3200000,
      "cacheReadMicroUsdPerMillion": 135000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "google",
    "modelId": "gemini-3.1-pro-preview",
    "hostModelId": "google/gemini-3.1-pro-preview",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 1,
      "outputPerMillion": 6,
      "cacheReadPerMillion": 0.1,
      "cacheWritePerMillion": 0.1875,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 1000000,
      "outputMicroUsdPerMillion": 6000000,
      "cacheReadMicroUsdPerMillion": 100000,
      "cacheWriteMicroUsdPerMillion": 187500,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "google",
    "modelId": "gemini-3.7-flash",
    "hostModelId": "google/gemini-3.7-flash",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.75,
      "outputPerMillion": 3.75,
      "cacheReadPerMillion": 0.075,
      "cacheWritePerMillion": 0.041667,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 750000,
      "outputMicroUsdPerMillion": 3750000,
      "cacheReadMicroUsdPerMillion": 75000,
      "cacheWriteMicroUsdPerMillion": 41667,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "google",
    "modelId": "gemini-3.8-flash",
    "hostModelId": "google/gemini-3.8-flash",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.75,
      "outputPerMillion": 3.75,
      "cacheReadPerMillion": 0.075,
      "cacheWritePerMillion": 0.041667,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 750000,
      "outputMicroUsdPerMillion": 3750000,
      "cacheReadMicroUsdPerMillion": 75000,
      "cacheWriteMicroUsdPerMillion": 41667,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "moonshot",
    "modelId": "kimi-k3",
    "hostModelId": "moonshotai/kimi-k3",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 3,
      "outputPerMillion": 15,
      "cacheReadPerMillion": 0.3,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 3000000,
      "outputMicroUsdPerMillion": 15000000,
      "cacheReadMicroUsdPerMillion": 300000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "openai",
    "modelId": "gpt-5.6-luna",
    "hostModelId": "openai/gpt-5.6-luna",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.2,
      "outputPerMillion": 1.2,
      "cacheReadPerMillion": 0.02,
      "cacheWritePerMillion": 0.25,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 200000,
      "outputMicroUsdPerMillion": 1200000,
      "cacheReadMicroUsdPerMillion": 20000,
      "cacheWriteMicroUsdPerMillion": 250000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "openai",
    "modelId": "gpt-5.6-sol",
    "hostModelId": "openai/gpt-5.6-sol",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 4,
      "outputPerMillion": 20,
      "cacheReadPerMillion": 0.4,
      "cacheWritePerMillion": 5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 4000000,
      "outputMicroUsdPerMillion": 20000000,
      "cacheReadMicroUsdPerMillion": 400000,
      "cacheWriteMicroUsdPerMillion": 5000000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "openai",
    "modelId": "gpt-5.6-terra",
    "hostModelId": "openai/gpt-5.6-terra",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 12,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 2.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 12000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 2500000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "openai",
    "modelId": "gpt-6-astra",
    "hostModelId": "openai/gpt-6-astra",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 10,
      "outputPerMillion": 50,
      "cacheReadPerMillion": 1,
      "cacheWritePerMillion": 12.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 10000000,
      "outputMicroUsdPerMillion": 50000000,
      "cacheReadMicroUsdPerMillion": 1000000,
      "cacheWriteMicroUsdPerMillion": 12500000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "openai",
    "modelId": "gpt-6-luna",
    "hostModelId": "openai/gpt-6-luna",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.1,
      "outputPerMillion": 0.5,
      "cacheReadPerMillion": 0.01,
      "cacheWritePerMillion": 0.125,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 100000,
      "outputMicroUsdPerMillion": 500000,
      "cacheReadMicroUsdPerMillion": 10000,
      "cacheWriteMicroUsdPerMillion": 125000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "openai",
    "modelId": "gpt-6-sol",
    "hostModelId": "openai/gpt-6-sol",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 10,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 2.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 10000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 2500000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "xai",
    "modelId": "grok-4.6",
    "hostModelId": "x-ai/grok-4.6",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 6,
      "cacheReadPerMillion": 0.5,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 6000000,
      "cacheReadMicroUsdPerMillion": 500000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "xai",
    "modelId": "grok-4.7",
    "hostModelId": "x-ai/grok-4.7",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 1.6,
      "outputPerMillion": 4.8,
      "cacheReadPerMillion": 0.4,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 1600000,
      "outputMicroUsdPerMillion": 4800000,
      "cacheReadMicroUsdPerMillion": 400000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "kilo",
    "provider": "zai",
    "modelId": "glm-5.3",
    "hostModelId": "z-ai/glm-5.3",
    "tariff": {
      "version": "kilo-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 1.4,
      "outputPerMillion": 4.4,
      "cacheReadPerMillion": 0.26,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 1400000,
      "outputMicroUsdPerMillion": 4400000,
      "cacheReadMicroUsdPerMillion": 260000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967",
      "KGW-2026-09-28"
    ]
  },
  {
    "host": "nvidia",
    "provider": "deepseek",
    "modelId": "deepseek-v4-pro",
    "hostModelId": "deepseek-ai/deepseek-v4-pro",
    "tariff": {
      "version": "nvidia-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.435,
      "outputPerMillion": 0.87,
      "cacheReadPerMillion": 0.003625,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 435000,
      "outputMicroUsdPerMillion": 870000,
      "cacheReadMicroUsdPerMillion": 3625,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "nvidia",
    "provider": "moonshot",
    "modelId": "kimi-k3",
    "hostModelId": "moonshotai/kimi-k3",
    "tariff": null,
    "tariffBasis": "free-tier",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "nvidia",
    "provider": "zai",
    "modelId": "glm-5.3",
    "hostModelId": "z-ai/glm-5.3",
    "tariff": null,
    "tariffBasis": "free-tier",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "anthropic",
    "modelId": "claude-fable-5-1",
    "hostModelId": "anthropic/claude-fable-5.1",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 10,
      "outputPerMillion": 50,
      "cacheReadPerMillion": 0.25,
      "cacheWritePerMillion": 12.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 10000000,
      "outputMicroUsdPerMillion": 50000000,
      "cacheReadMicroUsdPerMillion": 250000,
      "cacheWriteMicroUsdPerMillion": 12500000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "anthropic",
    "modelId": "claude-opus-5",
    "hostModelId": "anthropic/claude-opus-5",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 5,
      "outputPerMillion": 25,
      "cacheReadPerMillion": 0.5,
      "cacheWritePerMillion": 6.25,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 5000000,
      "outputMicroUsdPerMillion": 25000000,
      "cacheReadMicroUsdPerMillion": 500000,
      "cacheWriteMicroUsdPerMillion": 6250000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "anthropic",
    "modelId": "claude-opus-5-5",
    "hostModelId": "anthropic/claude-opus-5.5",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 4,
      "outputPerMillion": 20,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 4000000,
      "outputMicroUsdPerMillion": 20000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 5000000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "anthropic",
    "modelId": "claude-sonnet-5",
    "hostModelId": "anthropic/claude-sonnet-5",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 10,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 2.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 10000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 2500000,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "deepseek",
    "modelId": "deepseek-v4-pro",
    "hostModelId": "deepseek/deepseek-v4-pro",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.9483,
      "outputPerMillion": 1.8966,
      "cacheReadPerMillion": 0.079025,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 948300,
      "outputMicroUsdPerMillion": 1896600,
      "cacheReadMicroUsdPerMillion": 79025,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "google",
    "modelId": "gemini-3.1-pro-preview",
    "hostModelId": "google/gemini-3.1-pro-preview",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 12,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 0.375,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 12000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 375000,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 200000,
          "inputMultiplier": 2,
          "outputMultiplier": 1.5,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "google",
    "modelId": "gemini-3.7-flash",
    "hostModelId": "google/gemini-3.7-flash",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.75,
      "outputPerMillion": 3.75,
      "cacheReadPerMillion": 0.075,
      "cacheWritePerMillion": 0.041667,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 750000,
      "outputMicroUsdPerMillion": 3750000,
      "cacheReadMicroUsdPerMillion": 75000,
      "cacheWriteMicroUsdPerMillion": 41667,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "google",
    "modelId": "gemini-3.8-flash",
    "hostModelId": "google/gemini-3.8-flash",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.75,
      "outputPerMillion": 3.75,
      "cacheReadPerMillion": 0.075,
      "cacheWritePerMillion": 0.041667,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 750000,
      "outputMicroUsdPerMillion": 3750000,
      "cacheReadMicroUsdPerMillion": 75000,
      "cacheWriteMicroUsdPerMillion": 41667,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "moonshot",
    "modelId": "kimi-k3",
    "hostModelId": "moonshotai/kimi-k3",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 3,
      "outputPerMillion": 15,
      "cacheReadPerMillion": 0.3,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 3000000,
      "outputMicroUsdPerMillion": 15000000,
      "cacheReadMicroUsdPerMillion": 300000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "openai",
    "modelId": "gpt-5.6-luna",
    "hostModelId": "openai/gpt-5.6-luna",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.2,
      "outputPerMillion": 1.2,
      "cacheReadPerMillion": 0.02,
      "cacheWritePerMillion": 0.25,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 200000,
      "outputMicroUsdPerMillion": 1200000,
      "cacheReadMicroUsdPerMillion": 20000,
      "cacheWriteMicroUsdPerMillion": 250000,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 272000,
          "inputMultiplier": 2,
          "outputMultiplier": 1.5,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "openai",
    "modelId": "gpt-5.6-sol",
    "hostModelId": "openai/gpt-5.6-sol",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 10,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 2.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 10000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 2500000,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 272000,
          "inputMultiplier": 2,
          "outputMultiplier": 1.5,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "openai",
    "modelId": "gpt-5.6-terra",
    "hostModelId": "openai/gpt-5.6-terra",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 12,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 2.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 12000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 2500000,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 272000,
          "inputMultiplier": 2,
          "outputMultiplier": 1.5,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "openai",
    "modelId": "gpt-6-astra",
    "hostModelId": "openai/gpt-6-astra",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 10,
      "outputPerMillion": 50,
      "cacheReadPerMillion": 1,
      "cacheWritePerMillion": 12.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 10000000,
      "outputMicroUsdPerMillion": 50000000,
      "cacheReadMicroUsdPerMillion": 1000000,
      "cacheWriteMicroUsdPerMillion": 12500000,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 272000,
          "inputMultiplier": 2,
          "outputMultiplier": 1.5,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "openai",
    "modelId": "gpt-6-luna",
    "hostModelId": "openai/gpt-6-luna",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 0.1,
      "outputPerMillion": 0.5,
      "cacheReadPerMillion": 0.01,
      "cacheWritePerMillion": 0.125,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 100000,
      "outputMicroUsdPerMillion": 500000,
      "cacheReadMicroUsdPerMillion": 10000,
      "cacheWriteMicroUsdPerMillion": 125000,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 272000,
          "inputMultiplier": 2,
          "outputMultiplier": 1.5,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "openai",
    "modelId": "gpt-6-sol",
    "hostModelId": "openai/gpt-6-sol",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 10,
      "cacheReadPerMillion": 0.2,
      "cacheWritePerMillion": 2.5,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 10000000,
      "cacheReadMicroUsdPerMillion": 200000,
      "cacheWriteMicroUsdPerMillion": 2500000,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 272000,
          "inputMultiplier": 2,
          "outputMultiplier": 1.5,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "xai",
    "modelId": "grok-4.6",
    "hostModelId": "x-ai/grok-4.6",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 2,
      "outputPerMillion": 6,
      "cacheReadPerMillion": 0.5,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 2000000,
      "outputMicroUsdPerMillion": 6000000,
      "cacheReadMicroUsdPerMillion": 500000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 200000,
          "inputMultiplier": 2,
          "outputMultiplier": 2,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "xai",
    "modelId": "grok-4.7",
    "hostModelId": "x-ai/grok-4.7",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 1.6,
      "outputPerMillion": 4.8,
      "cacheReadPerMillion": 0.4,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 1600000,
      "outputMicroUsdPerMillion": 4800000,
      "cacheReadMicroUsdPerMillion": 400000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null,
      "tiers": [
        {
          "aboveInputTokens": 200000,
          "inputMultiplier": 2,
          "outputMultiplier": 2,
          "cacheMultiplier": 2
        }
      ]
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  },
  {
    "host": "openrouter",
    "provider": "zai",
    "modelId": "glm-5.3",
    "hostModelId": "z-ai/glm-5.3",
    "tariff": {
      "version": "openrouter-2026-09-28",
      "currency": "USD",
      "effectiveAt": "2026-09-28T00:00:00Z",
      "inputPerMillion": 1.4,
      "outputPerMillion": 4.4,
      "cacheReadPerMillion": 0.26,
      "cacheWritePerMillion": null,
      "sourceId": "MODELSDEV-2075e967",
      "inputMicroUsdPerMillion": 1400000,
      "outputMicroUsdPerMillion": 4400000,
      "cacheReadMicroUsdPerMillion": 260000,
      "cacheWriteMicroUsdPerMillion": null,
      "cacheWrite1hMicroUsdPerMillion": null
    },
    "tariffBasis": "host",
    "sourceIds": [
      "MODELSDEV-2075e967"
    ]
  }
] as Serving[]);
