/**
 * The non-Anthropic entries of the bundled snapshot `multi-2026-09-27` (owner decision DOMAINS
 * 7be3c43; SPEC §8.1 as amended 2026-09-27; admission review
 * `.planning/research/v1.2-spec-8.1-registry-review.md`, routing design e6aa62d §3.2).
 *
 * - The facts come from the research proposal (`.planning/research/v1.2-model-registry-proposal.json`,
 *   fetched 2026-09-26 and 2026-09-27) as the review re-read them. Every entry is `unevaluated` with
 *   no evaluation slice, so none is routed automatically before local outcomes or a signed release
 *   (a qualified board prior may only let it be explored, public-priors.ts).
 * - OpenAI above 272K input: 2x input and cache, 1.5x output, for the whole request. xAI at or above
 *   200K: 2x everything (`inclusive`). Gemini 3.1 Pro above 200K: 2x input and cache, 1.5x output.
 * - Gemini 3.8 and 3.7 Flash double on 2027-01-01 (a scheduled price). GPT-5.6 Sol's price is a
 *   promotion "available at least through November 21, 2026" (`validUntil`).
 * - DeepSeek bills half price off-peak; the registry holds the peak price, the upper bound (time-of-day
 *   pricing is a known schema gap).
 * - `gemini-3.1-pro-preview` is `preview`: advice and shadow only, never an automated route.
 * - Kimi K3 and DeepSeek train on content by default: `requiresProviderConsent`, so they are never
 *   routed, suggested or launched until the user grants the per-provider consent.
 * - Codex's starting effort differs per model (Astra `low`, Sol `medium`, Luna `high`), so the
 *   Codex rows carry it. Antigravity names the effort in the model slug (routing design §3.2); the
 *   slug spelling is to be confirmed against `agy models` on a certify run.
 * - `dataGovernance.bySignIn` holds the terms per sign-in; on a ChatGPT workspace, a Gemini unpaid key,
 *   an Antigravity login or a consumer plan the provider's own settings apply, and explain and doctor
 *   say so.
 */
import type { HarnessAccess, RoutingModel } from '@jevris/contracts';

/** The sources of the entries and access rows below, each with its fetch date. */
export const MULTI_REGISTRY_SOURCES: Readonly<Record<string, { readonly url: string; readonly fetchedOn: string }>> = Object.freeze({
  'AGY-FAQ': { url: 'https://antigravity.google/docs/faq/', fetchedOn: '2026-09-27' },
  'AGY-MODELS': { url: 'https://antigravity.google/docs/models/', fetchedOn: '2026-09-27' },
  'CODEX-AUTH': { url: 'https://learn.chatgpt.com/docs/auth', fetchedOn: '2026-09-27' },
  'CODEX-CHANGELOG': { url: 'https://learn.chatgpt.com/docs/changelog', fetchedOn: '2026-09-27' },
  'CODEX-MODELS': { url: 'https://learn.chatgpt.com/docs/models', fetchedOn: '2026-09-27' },
  'DS-ANTHROPIC': { url: 'https://api-docs.deepseek.com/guides/anthropic_api', fetchedOn: '2026-09-27' },
  'DS-HF-V41FLASH': { url: 'https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash', fetchedOn: '2026-09-27' },
  'DS-HF-V4PRO': { url: 'https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro', fetchedOn: '2026-09-26' },
  'DS-NEWS-0910': { url: 'https://api-docs.deepseek.com/news/news260910/', fetchedOn: '2026-09-27' },
  'DS-PRICING': { url: 'https://api-docs.deepseek.com/quick_start/pricing', fetchedOn: '2026-09-27' },
  'DS-PRIVACY': { url: 'https://cdn.deepseek.com/policies/en-US/deepseek-privacy-policy.html', fetchedOn: '2026-09-26' },
  'DS-THINK': { url: 'https://api-docs.deepseek.com/guides/thinking_mode/', fetchedOn: '2026-09-26' },
  'DS-UPDATES': { url: 'https://api-docs.deepseek.com/updates/', fetchedOn: '2026-09-27' },
  'GOO-CACHE': { url: 'https://ai.google.dev/gemini-api/docs/caching', fetchedOn: '2026-09-26' },
  'GOO-CARD-31PRO': { url: 'https://deepmind.google/models/model-cards/gemini-3-1-pro/', fetchedOn: '2026-09-26' },
  'GOO-EVAL-38': { url: 'https://storage.googleapis.com/deepmind-media/gemini/gemini_3-8_flash_model_evaluation.pdf', fetchedOn: '2026-09-26' },
  'GOO-M-gemini-3.1-pro-preview': { url: 'https://ai.google.dev/gemini-api/docs/models/gemini-3.1-pro-preview', fetchedOn: '2026-09-27' },
  'GOO-M-gemini-3.7-flash': { url: 'https://ai.google.dev/gemini-api/docs/models/gemini-3.7-flash', fetchedOn: '2026-09-27' },
  'GOO-M-gemini-3.8-flash': { url: 'https://ai.google.dev/gemini-api/docs/models/gemini-3.8-flash', fetchedOn: '2026-09-27' },
  'GOO-MODELS': { url: 'https://ai.google.dev/gemini-api/docs/models', fetchedOn: '2026-09-26' },
  'GOO-PRICING': { url: 'https://ai.google.dev/gemini-api/docs/pricing', fetchedOn: '2026-09-27' },
  'GOO-TERMS': { url: 'https://ai.google.dev/gemini-api/terms', fetchedOn: '2026-09-27' },
  'GOO-THINK': { url: 'https://ai.google.dev/gemini-api/docs/thinking', fetchedOn: '2026-09-27' },
  'IND-AA-AGENTS': { url: 'https://artificialanalysis.ai/agents/coding-agents', fetchedOn: '2026-09-26' },
  'IND-AA-MODELS': { url: 'https://artificialanalysis.ai/models', fetchedOn: '2026-09-26' },
  'IND-TBENCH': { url: 'https://www.tbench.ai/leaderboard', fetchedOn: '2026-09-26' },
  'KIMI-CC': { url: 'https://platform.kimi.ai/docs/guide/claude-code-kimi', fetchedOn: '2026-09-26' },
  'KIMI-HF-K3': { url: 'https://huggingface.co/moonshotai/Kimi-K3', fetchedOn: '2026-09-26' },
  'KIMI-PRICING': { url: 'https://platform.kimi.ai/docs/pricing/chat', fetchedOn: '2026-09-27' },
  'KIMI-PRIVACY': { url: 'https://platform.kimi.ai/docs/agreement/userprivacy', fetchedOn: '2026-09-27' },
  MODELSDEV: { url: 'https://github.com/sst/models.dev/tree/dev/providers', fetchedOn: '2026-09-26' },
  'OAI-CACHE': { url: 'https://developers.openai.com/api/docs/guides/prompt-caching', fetchedOn: '2026-09-27' },
  'OAI-CHANGELOG': { url: 'https://developers.openai.com/api/docs/changelog', fetchedOn: '2026-09-27' },
  'OAI-DATA': { url: 'https://developers.openai.com/api/docs/guides/your-data', fetchedOn: '2026-09-27' },
  'OAI-M-gpt-5.6-luna': { url: 'https://developers.openai.com/api/docs/models/gpt-5.6-luna', fetchedOn: '2026-09-27' },
  'OAI-M-gpt-5.6-sol': { url: 'https://developers.openai.com/api/docs/models/gpt-5.6-sol', fetchedOn: '2026-09-27' },
  'OAI-M-gpt-5.6-terra': { url: 'https://developers.openai.com/api/docs/models/gpt-5.6-terra', fetchedOn: '2026-09-27' },
  'OAI-M-gpt-6-astra': { url: 'https://developers.openai.com/api/docs/models/gpt-6-astra', fetchedOn: '2026-09-27' },
  'OAI-M-gpt-6-luna': { url: 'https://developers.openai.com/api/docs/models/gpt-6-luna', fetchedOn: '2026-09-27' },
  'OAI-M-gpt-6-sol': { url: 'https://developers.openai.com/api/docs/models/gpt-6-sol', fetchedOn: '2026-09-27' },
  'OAI-MODELS': { url: 'https://developers.openai.com/api/docs/models', fetchedOn: '2026-09-26' },
  'OAI-PRICING': { url: 'https://developers.openai.com/api/docs/pricing', fetchedOn: '2026-09-27' },
  'OAI-REASONING': { url: 'https://developers.openai.com/api/docs/guides/reasoning', fetchedOn: '2026-09-27' },
  'OR-GLM': { url: 'https://openrouter.ai/api/v1/models/z-ai/glm-5.3/endpoints', fetchedOn: '2026-09-26' },
  'OR-GROK': { url: 'https://openrouter.ai/api/v1/models/x-ai/grok-4.7/endpoints', fetchedOn: '2026-09-26' },
  'OR-KIMI': { url: 'https://openrouter.ai/api/v1/models/moonshotai/kimi-k3/endpoints', fetchedOn: '2026-09-26' },
  'VTX-M-gemini-3.1-pro-preview': { url: 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/gemini/3-1-pro', fetchedOn: '2026-09-27' },
  'VTX-M-gemini-3.7-flash': { url: 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/gemini/3-7-flash', fetchedOn: '2026-09-26' },
  'VTX-M-gemini-3.8-flash': { url: 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/gemini/3-8-flash', fetchedOn: '2026-09-26' },
  'XAI-46': { url: 'https://docs.x.ai/developers/models/grok-4.6', fetchedOn: '2026-09-26' },
  'XAI-47': { url: 'https://docs.x.ai/developers/models/grok-4.7', fetchedOn: '2026-09-26' },
  'XAI-47-GUIDE': { url: 'https://docs.x.ai/developers/grok-4-7', fetchedOn: '2026-09-26' },
  'XAI-CACHE': { url: 'https://docs.x.ai/developers/advanced-api-usage/prompt-caching', fetchedOn: '2026-09-26' },
  'XAI-MODELS': { url: 'https://docs.x.ai/docs/models', fetchedOn: '2026-09-26' },
  'XAI-NEWS-46': { url: 'https://x.ai/news/grok-4-6', fetchedOn: '2026-09-26' },
  'XAI-NEWS-47': { url: 'https://x.ai/news/grok-4-7', fetchedOn: '2026-09-26' },
  'XAI-PRICING': { url: 'https://docs.x.ai/developers/pricing', fetchedOn: '2026-09-26' },
  'XAI-RATE': { url: 'https://docs.x.ai/developers/rate-limits', fetchedOn: '2026-09-26' },
  'XAI-REASONING': { url: 'https://docs.x.ai/developers/model-capabilities/text/reasoning', fetchedOn: '2026-09-26' },
  'XAI-RELNOTES': { url: 'https://docs.x.ai/developers/release-notes', fetchedOn: '2026-09-26' },
  'XAI-SECURITY': { url: 'https://docs.x.ai/developers/faq/security', fetchedOn: '2026-09-26' },
  'ZAI-CC': { url: 'https://docs.z.ai/devpack/tool/claude', fetchedOn: '2026-09-26' },
  'ZAI-DEVPACK': { url: 'https://docs.z.ai/devpack/overview', fetchedOn: '2026-09-26' },
  'ZAI-GLM53': { url: 'https://docs.z.ai/guides/llm/glm-5.3', fetchedOn: '2026-09-27' },
  'ZAI-HF': { url: 'https://huggingface.co/zai-org/GLM-5.3', fetchedOn: '2026-09-27' },
  'ZAI-PRICING': { url: 'https://docs.z.ai/guides/overview/pricing', fetchedOn: '2026-09-27' },
  'ZAI-PRIVACY': { url: 'https://docs.z.ai/legal-agreement/privacy-policy', fetchedOn: '2026-09-27' },
  'ZAI-RELNOTES': { url: 'https://docs.z.ai/release-notes/new-released', fetchedOn: '2026-09-27' },});

export const MULTI_PROVIDER_ENTRIES: readonly RoutingModel[] = [
  {
    provider: 'openai',
    modelId: 'gpt-6-astra',
    family: 'gpt-6',
    displayName: 'GPT-6 Astra',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'reasoning-effort', 'fast-mode', 'explicit-cache'],
    contextTokens: 1050000,
    maxInputTokens: 922000,
    maxOutputTokens: 128000,
    effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'],
    regions: ['global', 'us', 'eu'],
    health: 'unknown',
    tariff: {version: 'openai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 10, outputPerMillion: 50, cacheReadPerMillion: 1, cacheWritePerMillion: 12.5, sourceId: 'OAI-PRICING', tiers: [{aboveInputTokens: 272000, inputMultiplier: 2, outputMultiplier: 1.5, cacheMultiplier: 2}], inputMicroUsdPerMillion: 10000000, outputMicroUsdPerMillion: 50000000, cacheReadMicroUsdPerMillion: 1000000, cacheWriteMicroUsdPerMillion: 12500000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-09-03T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'OAI-CHANGELOG'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'OAI-DATA', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'OAI-DATA'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}, {signIn: 'workspace', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}]},
    cache: {mode: 'both', ttls: ['30m'], minTokens: 1024, perModel: true},
    harnessModels: [{harness: 'codex', id: 'gpt-6-astra', effortVia: 'config', defaultEffort: 'low'}],
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['OAI-PRICING', 'OAI-MODELS', 'OAI-CACHE', 'OAI-REASONING', 'OAI-M-gpt-6-astra', 'OAI-CHANGELOG', 'OAI-DATA'],
  },
  {
    provider: 'openai',
    modelId: 'gpt-6-sol',
    family: 'gpt-6',
    displayName: 'GPT-6 Sol',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'reasoning-effort', 'fast-mode', 'explicit-cache'],
    contextTokens: 1050000,
    maxOutputTokens: 128000,
    effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    regions: ['global', 'eu'],
    health: 'unknown',
    tariff: {version: 'openai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 2, outputPerMillion: 10, cacheReadPerMillion: 0.2, cacheWritePerMillion: 2.5, sourceId: 'OAI-PRICING', tiers: [{aboveInputTokens: 272000, inputMultiplier: 2, outputMultiplier: 1.5, cacheMultiplier: 2}], inputMicroUsdPerMillion: 2000000, outputMicroUsdPerMillion: 10000000, cacheReadMicroUsdPerMillion: 200000, cacheWriteMicroUsdPerMillion: 2500000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-09-22T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'CODEX-CHANGELOG'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'OAI-DATA', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'OAI-DATA'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}, {signIn: 'workspace', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}]},
    cache: {mode: 'both', ttls: ['30m'], minTokens: 1024, perModel: true},
    harnessModels: [{harness: 'codex', id: 'gpt-6-sol', effortVia: 'config', defaultEffort: 'medium'}],
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['OAI-PRICING', 'OAI-MODELS', 'OAI-CACHE', 'OAI-REASONING', 'OAI-M-gpt-6-sol', 'OAI-CHANGELOG', 'CODEX-CHANGELOG'],
  },
  {
    provider: 'openai',
    modelId: 'gpt-6-luna',
    family: 'gpt-6',
    displayName: 'GPT-6 Luna',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'reasoning-effort', 'fast-mode', 'explicit-cache'],
    contextTokens: 1050000,
    maxOutputTokens: 128000,
    effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    regions: ['global', 'eu'],
    health: 'unknown',
    tariff: {version: 'openai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 0.1, outputPerMillion: 0.5, cacheReadPerMillion: 0.01, cacheWritePerMillion: 0.125, sourceId: 'OAI-PRICING', tiers: [{aboveInputTokens: 272000, inputMultiplier: 2, outputMultiplier: 1.5, cacheMultiplier: 2}], inputMicroUsdPerMillion: 100000, outputMicroUsdPerMillion: 500000, cacheReadMicroUsdPerMillion: 10000, cacheWriteMicroUsdPerMillion: 125000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: null, retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'CODEX-CHANGELOG'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'OAI-DATA', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'OAI-DATA'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}, {signIn: 'workspace', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}]},
    cache: {mode: 'both', ttls: ['30m'], minTokens: 1024, perModel: true},
    harnessModels: [{harness: 'codex', id: 'gpt-6-luna', effortVia: 'config', defaultEffort: 'high'}],
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['OAI-PRICING', 'OAI-MODELS', 'OAI-CACHE', 'OAI-REASONING', 'OAI-M-gpt-6-luna', 'OAI-CHANGELOG', 'CODEX-CHANGELOG'],
  },
  {
    provider: 'openai',
    modelId: 'gpt-5.6-sol',
    family: 'gpt-5.6',
    displayName: 'GPT-5.6 Sol',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'reasoning-effort', 'fast-mode', 'explicit-cache'],
    contextTokens: 1050000,
    maxOutputTokens: 128000,
    effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    regions: ['global'],
    health: 'unknown',
    tariff: {version: 'openai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 4, outputPerMillion: 20, cacheReadPerMillion: 0.4, cacheWritePerMillion: 5, sourceId: 'OAI-PRICING', inputMicroUsdPerMillion: 4000000, outputMicroUsdPerMillion: 20000000, cacheReadMicroUsdPerMillion: 400000, cacheWriteMicroUsdPerMillion: 5000000, cacheWrite1hMicroUsdPerMillion: null, validUntil: '2026-11-22T00:00:00Z'},
    lifecycle: {status: 'active', releasedOn: '2026-07-09T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'OAI-CHANGELOG'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'OAI-DATA', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'OAI-DATA'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}, {signIn: 'workspace', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}]},
    cache: {mode: 'both', ttls: ['30m'], minTokens: 1024, perModel: true},
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['OAI-PRICING', 'OAI-MODELS', 'OAI-CACHE', 'OAI-REASONING', 'OAI-M-gpt-5.6-sol', 'OAI-CHANGELOG'],
  },
  {
    provider: 'openai',
    modelId: 'gpt-5.6-terra',
    family: 'gpt-5.6',
    displayName: 'GPT-5.6 Terra',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'reasoning-effort', 'fast-mode', 'explicit-cache'],
    contextTokens: 1050000,
    maxOutputTokens: 128000,
    effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    regions: ['global'],
    health: 'unknown',
    tariff: {version: 'openai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 2, outputPerMillion: 12, cacheReadPerMillion: 0.2, cacheWritePerMillion: 2.5, sourceId: 'OAI-PRICING', inputMicroUsdPerMillion: 2000000, outputMicroUsdPerMillion: 12000000, cacheReadMicroUsdPerMillion: 200000, cacheWriteMicroUsdPerMillion: 2500000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-07-09T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'OAI-CHANGELOG'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'OAI-DATA', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'OAI-DATA'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}, {signIn: 'workspace', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}]},
    cache: {mode: 'both', ttls: ['30m'], minTokens: 1024, perModel: true},
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['OAI-PRICING', 'OAI-MODELS', 'OAI-CACHE', 'OAI-REASONING', 'OAI-M-gpt-5.6-terra', 'OAI-CHANGELOG'],
  },
  {
    provider: 'openai',
    modelId: 'gpt-5.6-luna',
    family: 'gpt-5.6',
    displayName: 'GPT-5.6 Luna',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'reasoning-effort', 'fast-mode', 'explicit-cache'],
    contextTokens: 1050000,
    maxOutputTokens: 128000,
    effortLevels: ['none', 'low', 'medium', 'high', 'xhigh', 'max'],
    regions: ['global'],
    health: 'unknown',
    tariff: {version: 'openai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 0.2, outputPerMillion: 1.2, cacheReadPerMillion: 0.02, cacheWritePerMillion: 0.25, sourceId: 'OAI-PRICING', inputMicroUsdPerMillion: 200000, outputMicroUsdPerMillion: 1200000, cacheReadMicroUsdPerMillion: 20000, cacheWriteMicroUsdPerMillion: 250000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-07-09T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'OAI-CHANGELOG'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'OAI-DATA', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'OAI-DATA'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}, {signIn: 'workspace', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'WORKSPACE_SETTINGS_APPLY', sourceId: 'CODEX-AUTH'}]},
    cache: {mode: 'both', ttls: ['30m'], minTokens: 1024, perModel: true},
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['OAI-PRICING', 'OAI-MODELS', 'OAI-CACHE', 'OAI-REASONING', 'OAI-M-gpt-5.6-luna', 'OAI-CHANGELOG'],
  },
  {
    provider: 'google',
    modelId: 'gemini-3.8-flash',
    family: 'gemini-flash',
    displayName: 'Gemini 3.8 Flash',
    capabilities: ['text', 'vision', 'audio-input', 'video-input', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'thinking-level', 'thought-signatures', 'computer-use-preview', 'zdr'],
    contextTokens: 1048576,
    maxOutputTokens: 65536,
    effortLevels: ['low', 'medium', 'high'],
    defaultEffort: 'medium',
    regions: ['global'],
    health: 'unknown',
    tariff: {version: 'google-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 0.75, outputPerMillion: 3.75, cacheReadPerMillion: 0.075, cacheWritePerMillion: 0.75, sourceId: 'GOO-PRICING', scheduled: [{effectiveAt: '2027-01-01T00:00:00Z', inputPerMillion: 1.5, outputPerMillion: 7.5, cacheReadPerMillion: 0.15, cacheWritePerMillion: 1.5, sourceId: 'GOO-PRICING', inputMicroUsdPerMillion: 1500000, outputMicroUsdPerMillion: 7500000, cacheReadMicroUsdPerMillion: 150000, cacheWriteMicroUsdPerMillion: 1500000}], inputMicroUsdPerMillion: 750000, outputMicroUsdPerMillion: 3750000, cacheReadMicroUsdPerMillion: 75000, cacheWriteMicroUsdPerMillion: 750000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-09-02T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'GOO-PRICING'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'GOO-TERMS', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: null, location: null, reasonCode: 'PAID_TIER_NO_TRAINING', sourceId: 'GOO-TERMS'}, {signIn: 'unpaid', trainsOnContent: true, retentionDays: null, location: null, reasonCode: 'UNPAID_TIER_TRAINS_OUTSIDE_EEA_CH_UK', sourceId: 'GOO-TERMS'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'ANTIGRAVITY_COLLECTION_ON_BY_DEFAULT', sourceId: 'AGY-FAQ'}]},
    harnessModels: [{harness: 'antigravity', id: 'gemini-3.8-flash-medium', effortVia: 'model-name', efforts: {low: 'gemini-3.8-flash-low', medium: 'gemini-3.8-flash-medium', high: 'gemini-3.8-flash-high'}, effortLevels: ['low', 'medium', 'high'], defaultEffort: 'medium'}],
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['GOO-MODELS', 'GOO-PRICING', 'GOO-THINK', 'GOO-CACHE', 'GOO-M-gemini-3.8-flash', 'VTX-M-gemini-3.8-flash', 'GOO-EVAL-38', 'AGY-MODELS'],
  },
  {
    provider: 'google',
    modelId: 'gemini-3.7-flash',
    family: 'gemini-flash',
    displayName: 'Gemini 3.7 Flash',
    capabilities: ['text', 'vision', 'audio-input', 'video-input', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'thinking-level', 'thought-signatures', 'computer-use-preview', 'zdr'],
    contextTokens: 1048576,
    maxOutputTokens: 65536,
    effortLevels: ['low', 'medium', 'high'],
    defaultEffort: 'medium',
    regions: ['global'],
    health: 'unknown',
    tariff: {version: 'google-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 0.75, outputPerMillion: 3.75, cacheReadPerMillion: 0.075, cacheWritePerMillion: 0.75, sourceId: 'GOO-PRICING', scheduled: [{effectiveAt: '2027-01-01T00:00:00Z', inputPerMillion: 1.5, outputPerMillion: 7.5, cacheReadPerMillion: 0.15, cacheWritePerMillion: 1.5, sourceId: 'GOO-PRICING', inputMicroUsdPerMillion: 1500000, outputMicroUsdPerMillion: 7500000, cacheReadMicroUsdPerMillion: 150000, cacheWriteMicroUsdPerMillion: 1500000}], inputMicroUsdPerMillion: 750000, outputMicroUsdPerMillion: 3750000, cacheReadMicroUsdPerMillion: 75000, cacheWriteMicroUsdPerMillion: 750000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-08-13T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'GOO-PRICING'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'GOO-TERMS', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: null, location: null, reasonCode: 'PAID_TIER_NO_TRAINING', sourceId: 'GOO-TERMS'}, {signIn: 'unpaid', trainsOnContent: true, retentionDays: null, location: null, reasonCode: 'UNPAID_TIER_TRAINS_OUTSIDE_EEA_CH_UK', sourceId: 'GOO-TERMS'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'ANTIGRAVITY_COLLECTION_ON_BY_DEFAULT', sourceId: 'AGY-FAQ'}]},
    harnessModels: [{harness: 'antigravity', id: 'gemini-3.7-flash-medium', effortVia: 'model-name', efforts: {low: 'gemini-3.7-flash-low', medium: 'gemini-3.7-flash-medium', high: 'gemini-3.7-flash-high'}, effortLevels: ['low', 'medium', 'high'], defaultEffort: 'medium'}],
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['GOO-MODELS', 'GOO-PRICING', 'GOO-THINK', 'GOO-CACHE', 'GOO-M-gemini-3.7-flash', 'VTX-M-gemini-3.7-flash', 'AGY-MODELS'],
  },
  {
    provider: 'google',
    modelId: 'gemini-3.1-pro-preview',
    family: 'gemini-pro',
    displayName: 'Gemini 3.1 Pro Preview',
    capabilities: ['text', 'vision', 'audio-input', 'video-input', 'tools', 'structured-output', 'code', 'prompt-caching', 'batch', 'thinking-level', 'thought-signatures', 'preview', 'zdr'],
    contextTokens: 1048576,
    maxOutputTokens: 65536,
    effortLevels: ['low', 'medium', 'high'],
    regions: ['global'],
    health: 'unknown',
    tariff: {version: 'google-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 2, outputPerMillion: 12, cacheReadPerMillion: 0.2, cacheWritePerMillion: 2, sourceId: 'GOO-PRICING', tiers: [{aboveInputTokens: 200000, inputMultiplier: 2, outputMultiplier: 1.5, cacheMultiplier: 2}], inputMicroUsdPerMillion: 2000000, outputMicroUsdPerMillion: 12000000, cacheReadMicroUsdPerMillion: 200000, cacheWriteMicroUsdPerMillion: 2000000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'preview', releasedOn: null, retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'GOO-M-gemini-3.1-pro-preview'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'GOO-TERMS', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: null, location: null, reasonCode: 'PAID_TIER_NO_TRAINING', sourceId: 'GOO-TERMS'}, {signIn: 'unpaid', trainsOnContent: true, retentionDays: null, location: null, reasonCode: 'UNPAID_TIER_TRAINS_OUTSIDE_EEA_CH_UK', sourceId: 'GOO-TERMS'}, {signIn: 'subscription', trainsOnContent: null, retentionDays: null, location: null, reasonCode: 'ANTIGRAVITY_COLLECTION_ON_BY_DEFAULT', sourceId: 'AGY-FAQ'}]},
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['GOO-MODELS', 'GOO-PRICING', 'GOO-THINK', 'GOO-CACHE', 'GOO-M-gemini-3.1-pro-preview', 'VTX-M-gemini-3.1-pro-preview', 'GOO-CARD-31PRO', 'AGY-MODELS'],
  },
  {
    provider: 'xai',
    modelId: 'grok-4.7',
    family: 'grok',
    displayName: 'Grok 4.7',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'thinking-always-on', 'reasoning-effort', 'fast-mode', 'inference-geo', 'zdr', 'responses-api'],
    contextTokens: 500000,
    maxOutputTokens: 450000,
    effortLevels: ['low', 'medium', 'high', 'xhigh'],
    defaultEffort: 'high',
    regions: ['us'],
    health: 'unknown',
    tariff: {version: 'xai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 2, outputPerMillion: 6, cacheReadPerMillion: 0.5, cacheWritePerMillion: 2, sourceId: 'XAI-PRICING', tiers: [{aboveInputTokens: 200000, inputMultiplier: 2, outputMultiplier: 2, cacheMultiplier: 2, inclusive: true}], inputMicroUsdPerMillion: 2000000, outputMicroUsdPerMillion: 6000000, cacheReadMicroUsdPerMillion: 500000, cacheWriteMicroUsdPerMillion: 2000000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-09-21T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'XAI-RELNOTES'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'XAI-SECURITY', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'XAI-SECURITY'}]},
    effortSwitch: {keepsCache: false, betaHeader: null, platforms: []},
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['XAI-PRICING', 'XAI-MODELS', 'XAI-47', 'XAI-47-GUIDE', 'XAI-REASONING', 'XAI-CACHE', 'XAI-RATE', 'XAI-SECURITY', 'XAI-RELNOTES', 'XAI-NEWS-47', 'OR-GROK', 'IND-TBENCH', 'IND-AA-AGENTS', 'IND-AA-MODELS'],
  },
  {
    provider: 'xai',
    modelId: 'grok-4.6',
    family: 'grok',
    displayName: 'Grok 4.6',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'thinking-always-on', 'reasoning-effort', 'fast-mode', 'inference-geo', 'zdr', 'responses-api'],
    contextTokens: 500000,
    maxOutputTokens: 450000,
    effortLevels: ['low', 'medium', 'high', 'xhigh'],
    defaultEffort: 'high',
    regions: ['us'],
    health: 'unknown',
    tariff: {version: 'xai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 2, outputPerMillion: 6, cacheReadPerMillion: 0.5, cacheWritePerMillion: 2, sourceId: 'XAI-PRICING', tiers: [{aboveInputTokens: 200000, inputMultiplier: 2, outputMultiplier: 2, cacheMultiplier: 2, inclusive: true}], inputMicroUsdPerMillion: 2000000, outputMicroUsdPerMillion: 6000000, cacheReadMicroUsdPerMillion: 500000, cacheWriteMicroUsdPerMillion: 2000000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-08-12T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'XAI-RELNOTES'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'XAI-SECURITY', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 30, location: null, reasonCode: 'API_NO_TRAINING', sourceId: 'XAI-SECURITY'}]},
    effortSwitch: {keepsCache: false, betaHeader: null, platforms: []},
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['XAI-PRICING', 'XAI-MODELS', 'XAI-46', 'XAI-REASONING', 'XAI-CACHE', 'XAI-RATE', 'XAI-SECURITY', 'XAI-RELNOTES', 'XAI-NEWS-46', 'OR-GROK', 'IND-TBENCH', 'IND-AA-AGENTS', 'IND-AA-MODELS'],
  },
  {
    provider: 'zai',
    modelId: 'glm-5.3',
    family: 'glm',
    displayName: 'GLM-5.3',
    capabilities: ['text', 'tools', 'json-mode', 'code', 'prompt-caching', 'reasoning-effort', 'thinking-always-on', 'open-weights', 'anthropic-compatible-endpoint'],
    contextTokens: 1000000,
    maxOutputTokens: 128000,
    effortLevels: ['low', 'high', 'max'],
    defaultEffort: 'max',
    regions: ['sg'],
    health: 'unknown',
    tariff: {version: 'zai-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 1.4, outputPerMillion: 4.4, cacheReadPerMillion: 0.26, cacheWritePerMillion: 1.4, sourceId: 'ZAI-PRICING', inputMicroUsdPerMillion: 1400000, outputMicroUsdPerMillion: 4400000, cacheReadMicroUsdPerMillion: 260000, cacheWriteMicroUsdPerMillion: 1400000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: null, retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'ZAI-RELNOTES'},
    dataGovernance: {zdrEligible: true, requiredRetentionDays: null, sourceId: 'ZAI-PRIVACY', bySignIn: [{signIn: 'api-key', trainsOnContent: false, retentionDays: 0, location: 'sg', reasonCode: 'NO_CONTENT_STORED', sourceId: 'ZAI-PRIVACY'}]},
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['ZAI-PRICING', 'ZAI-GLM53', 'ZAI-DEVPACK', 'ZAI-CC', 'ZAI-HF', 'OR-GLM', 'ZAI-RELNOTES'],
  },
  {
    provider: 'moonshot',
    modelId: 'kimi-k3',
    family: 'kimi',
    displayName: 'Kimi K3',
    capabilities: ['text', 'vision', 'tools', 'structured-output', 'code', 'prompt-caching', 'reasoning-effort', 'open-weights', 'anthropic-compatible-endpoint'],
    contextTokens: 1048576,
    maxOutputTokens: 943718,
    effortLevels: ['low', 'high', 'max'],
    defaultEffort: 'max',
    regions: ['unspecified', 'cn'],
    health: 'unknown',
    tariff: {version: 'moonshot-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 3, outputPerMillion: 15, cacheReadPerMillion: 0.3, cacheWritePerMillion: 3, sourceId: 'KIMI-PRICING', inputMicroUsdPerMillion: 3000000, outputMicroUsdPerMillion: 15000000, cacheReadMicroUsdPerMillion: 300000, cacheWriteMicroUsdPerMillion: 3000000, cacheWrite1hMicroUsdPerMillion: null},
    dataGovernance: {zdrEligible: false, requiredRetentionDays: null, sourceId: 'KIMI-PRIVACY', bySignIn: [{signIn: 'api-key', trainsOnContent: true, retentionDays: null, location: 'sg', reasonCode: 'TRAINS_ON_CONTENT', sourceId: 'KIMI-PRIVACY'}]},
    requiresProviderConsent: true,
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['KIMI-PRICING', 'KIMI-HF-K3', 'KIMI-CC', 'OR-KIMI', 'MODELSDEV'],
  },
  {
    provider: 'deepseek',
    modelId: 'deepseek-v4-pro',
    family: 'deepseek-v4',
    displayName: 'DeepSeek V4 Pro',
    capabilities: ['text', 'tools', 'json-mode', 'code', 'prompt-caching', 'reasoning-effort', 'thinking-toggle', 'open-weights', 'anthropic-compatible-endpoint', 'responses-api'],
    contextTokens: 1000000,
    maxOutputTokens: 393216,
    effortLevels: ['low', 'high', 'max'],
    regions: ['cn'],
    health: 'unknown',
    tariff: {version: 'deepseek-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 1.32, outputPerMillion: 3.96, cacheReadPerMillion: 0.044, cacheWritePerMillion: 1.32, sourceId: 'DS-PRICING', inputMicroUsdPerMillion: 1320000, outputMicroUsdPerMillion: 3960000, cacheReadMicroUsdPerMillion: 44000, cacheWriteMicroUsdPerMillion: 1320000, cacheWrite1hMicroUsdPerMillion: null},
    lifecycle: {status: 'active', releasedOn: '2026-08-13T00:00:00Z', retirementNotBefore: null, retiresOn: null, replacementModelId: null, sourceId: 'DS-UPDATES'},
    dataGovernance: {zdrEligible: false, requiredRetentionDays: null, sourceId: 'DS-PRIVACY', bySignIn: [{signIn: 'api-key', trainsOnContent: true, retentionDays: null, location: 'cn', reasonCode: 'TRAINS_BY_DEFAULT_OPT_OUT', sourceId: 'DS-PRIVACY'}]},
    requiresProviderConsent: true,
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['DS-PRICING', 'DS-NEWS-0910', 'DS-UPDATES', 'DS-HF-V4PRO', 'DS-ANTHROPIC'],
  },
  {
    provider: 'deepseek',
    modelId: 'deepseek-flash',
    family: 'deepseek-v4',
    displayName: 'DeepSeek V4.1 Flash',
    capabilities: ['text', 'vision', 'tools', 'json-mode', 'code', 'prompt-caching', 'reasoning-effort', 'thinking-toggle', 'open-weights', 'anthropic-compatible-endpoint', 'responses-api'],
    contextTokens: 1000000,
    maxOutputTokens: 393216,
    effortLevels: ['low', 'high', 'max'],
    regions: ['cn'],
    health: 'unknown',
    tariff: {version: 'deepseek-2026-09-26', currency: 'USD', effectiveAt: '2026-09-26T00:00:00Z', inputPerMillion: 0.3, outputPerMillion: 1.2, cacheReadPerMillion: 0.006, cacheWritePerMillion: 0.3, sourceId: 'DS-PRICING', inputMicroUsdPerMillion: 300000, outputMicroUsdPerMillion: 1200000, cacheReadMicroUsdPerMillion: 6000, cacheWriteMicroUsdPerMillion: 300000, cacheWrite1hMicroUsdPerMillion: null},
    dataGovernance: {zdrEligible: false, requiredRetentionDays: null, sourceId: 'DS-PRIVACY', bySignIn: [{signIn: 'api-key', trainsOnContent: true, retentionDays: null, location: 'cn', reasonCode: 'TRAINS_BY_DEFAULT_OPT_OUT', sourceId: 'DS-PRIVACY'}]},
    requiresProviderConsent: true,
    accountEligibility: [],
    evaluationSliceIds: [],
    evaluationVersion: 'unevaluated',
    discoveredVia: 'vendor-docs',
    sourceIds: ['DS-PRICING', 'DS-NEWS-0910', 'DS-THINK', 'DS-ANTHROPIC', 'DS-PRIVACY', 'MODELSDEV', 'DS-HF-V41FLASH'],
  },];

/**
 * How each harness reaches these providers (review §4; routing design §3.2; owner 7be3c43 for the
 * Antigravity native row). A row only narrows: a model becomes eligible on a harness from local
 * evidence (it ran there, or the harness lists it), never from the map alone. A row without
 * `idTemplate` names no model there until a model's own `harnessModels` row or a listing does.
 *
 * Kilo (2026-09-27): Kilo resolves `provider_id/model_id` against the models.dev catalog it ships
 * and refreshes hourly (KILO-CATALOG), so its direct provider ids are models.dev's, the same as
 * OpenCode's: `google`/`google-vertex`, `zai`/`zai-coding-plan`, `moonshotai`/`moonshotai-cn`,
 * `deepseek`. Kilo also reaches these models through its own gateway, models.dev provider `kilo`
 * ("Kilo Gateway"), as `kilo/<gateway provider>/<model>` (for example `kilo/z-ai/glm-5.3`,
 * `kilo/moonshotai/kimi-k3`, `kilo/google/gemini-3.8-flash`, `kilo/deepseek/deepseek-v4-pro`;
 * `deepseek-flash` is not on the gateway). The map holds one row per harness and provider, so the
 * gateway path is not a row here: a gateway run is not a direct provider run (it may fall back to
 * another model), and a gateway id is not mapped back to a registry entry yet.
 */
export const MULTI_PROVIDER_HARNESS_ACCESS: readonly HarnessAccess[] = [
  { harness: 'codex', provider: 'openai', access: 'native', sourceIds: ['CODEX-MODELS', 'CODEX-AUTH'], idTemplate: '{id}', signIns: ['api-key', 'subscription', 'workspace'], unattendedAllowed: true, effortVia: 'config', effortLevels: ['low', 'medium', 'high', 'xhigh', 'max'] },
  { harness: 'opencode', provider: 'openai', access: 'provider-config', sourceIds: ['OC-PROVIDERS', 'MODELSDEV'], providerIds: ['openai'], idTemplate: '{provider}/{id}', signIns: ['api-key', 'subscription'], effortVia: 'variant' },
  { harness: 'kilocode', provider: 'openai', access: 'provider-config', sourceIds: ['KILO-MODELS'], providerIds: ['openai'], idTemplate: '{provider}/{id}', signIns: ['api-key'], effortVia: 'variant' },
  { harness: 'antigravity', provider: 'google', access: 'native', sourceIds: ['AGY-MODELS', 'AGY-FAQ'], signIns: ['subscription', 'workspace', 'unpaid'], unattendedAllowed: true, effortVia: 'model-name' },
  { harness: 'opencode', provider: 'google', access: 'provider-config', sourceIds: ['OC-PROVIDERS', 'MODELSDEV'], providerIds: ['google', 'google-vertex'], idTemplate: '{provider}/{id}', signIns: ['api-key', 'unpaid'], effortVia: 'variant' },
  { harness: 'kilocode', provider: 'google', access: 'provider-config', sourceIds: ['KILO-MODELS', 'KILO-CATALOG', 'MODELSDEV'], providerIds: ['google', 'google-vertex'], idTemplate: '{provider}/{id}', signIns: ['api-key', 'unpaid'], effortVia: 'variant' },
  { harness: 'opencode', provider: 'xai', access: 'provider-config', sourceIds: ['OC-PROVIDERS', 'MODELSDEV'], providerIds: ['xai'], idTemplate: '{provider}/{id}', signIns: ['api-key', 'subscription'], effortVia: 'variant' },
  { harness: 'kilocode', provider: 'xai', access: 'provider-config', sourceIds: ['KILO-MODELS'], providerIds: ['xai'], idTemplate: '{provider}/{id}', signIns: ['api-key', 'subscription'], effortVia: 'variant' },
  { harness: 'opencode', provider: 'zai', access: 'provider-config', sourceIds: ['OC-PROVIDERS', 'MODELSDEV'], providerIds: ['zai', 'zai-coding-plan'], idTemplate: '{provider}/{id}', signIns: ['api-key', 'subscription'], effortVia: 'variant' },
  { harness: 'kilocode', provider: 'zai', access: 'provider-config', sourceIds: ['KILO-MODELS', 'KILO-CATALOG', 'MODELSDEV'], providerIds: ['zai', 'zai-coding-plan'], idTemplate: '{provider}/{id}', signIns: ['api-key', 'subscription'], effortVia: 'variant' },
  { harness: 'opencode', provider: 'moonshot', access: 'provider-config', sourceIds: ['OC-PROVIDERS', 'MODELSDEV'], providerIds: ['moonshotai', 'moonshotai-cn'], idTemplate: '{provider}/{id}', signIns: ['api-key'], effortVia: 'variant' },
  { harness: 'kilocode', provider: 'moonshot', access: 'provider-config', sourceIds: ['KILO-MODELS', 'KILO-CATALOG', 'MODELSDEV'], providerIds: ['moonshotai', 'moonshotai-cn'], idTemplate: '{provider}/{id}', signIns: ['api-key'], effortVia: 'variant' },
  { harness: 'opencode', provider: 'deepseek', access: 'provider-config', sourceIds: ['OC-PROVIDERS', 'MODELSDEV'], providerIds: ['deepseek'], idTemplate: '{provider}/{id}', signIns: ['api-key'], effortVia: 'variant' },
  { harness: 'kilocode', provider: 'deepseek', access: 'provider-config', sourceIds: ['KILO-MODELS', 'KILO-CATALOG', 'MODELSDEV'], providerIds: ['deepseek'], idTemplate: '{provider}/{id}', signIns: ['api-key'], effortVia: 'variant' },
];
