export {
  calibrationReleasePath,
  envValue,
  installReceiptPath,
  isPacksPath,
  jevrisPaths,
  jevrisRoots,
  packsDir,
  pathApiFor,
  resolveHome,
  type EnvLike,
  type HomeSource,
  type JevrisPaths,
  type JevrisPathsInput,
} from './paths.js';
export { legacyLeftovers, legacyPairs, migrateLegacyLayout, type MigrationFs, type MigrationReport } from './migrate.js';
export {
  RETRYABLE_RENAME_CODES,
  durableWrite,
  isTempFor,
  removeStaleTemps,
  renameWithRetry,
  tempNameFor,
  type DurableFs,
  type DurableHandle,
  type DurableWriteOptions,
  type DurableWriteResult,
} from './durable-write.js';
export {
  anchoredClock,
  createDeadline,
  elapsedSinceForeignStart,
  monotonicClock,
  monotonicNow,
  type Clock,
  type Deadline,
} from './clock.js';
export { SHARED_READ_TRIES, TRANSIENT_READ_CODES, readSharedFileSync, retryTransientSync } from './shared-read.js';
export { shellQuote } from './shell-quote.js';
export {
  escapeCmdArgument,
  escapeCmdCommand,
  isCmdShim,
  pathExtensions,
  planSpawn,
  resolveExecutable,
  runSync,
  type ResolveOptions,
  type RunSyncOptions,
  type RunSyncResult,
  type SpawnPlan,
} from './spawn.js';
export {
  canonicalPath,
  caseInsensitiveFs,
  hasParentSegment,
  isAbsoluteFor,
  isAbsoluteOnAnyPlatform,
  isInsideOrSame,
  isStrictlyInside,
  pathKey,
  sameFile,
  samePath,
  type CanonicalOptions,
} from './path-identity.js';
export {
  PRIVATE_DIR_MODE,
  PRIVATE_FILE_MODE,
  aclIsOwnerOnly,
  applyOwnerOnlyAcl,
  assertOwnerOnly,
  currentUser,
  ensurePrivateDir,
  parseIcacls,
  parseWhoami,
  setPrivateUmask,
  tightenPrivateFile,
  writePrivateFile,
  type AclEntry,
  type CurrentUser,
  type ExecPort,
  type ExecResult,
  type OwnerOnlyCheck,
  type OwnerOnlyOptions,
  type PrivateResult,
  type PrivateStat,
} from './owner-only.js';
export {
  MACHINE_ID_EXEC_TIMEOUT_MS,
  hostnameCandidates,
  machineIdentity,
  parseIoregPlatformUuid,
  parseMachineIdFile,
  parseRegMachineGuid,
  readMachineIdentity,
  type HostnameCandidateOptions,
  type MachineIdOptions,
  type MachineIdSource,
  type MachineIdentity,
  type MachineIdentityFailure,
  type MachineIdentityResult,
} from './machine-id.js';
export { BETTER_SQLITE3, nativeDiagnostic, probeNativeAddon, type NativeAddonSpec, type NativeProbe, type ProbeOptions } from './native.js';
export { PACKAGE_NAMES, assetPath, findPackageRoot, packageRoot, type PackageRootOptions } from './package-root.js';
export {
  AUTHORITY_FILE_REFUSALS,
  authorityFileRefusal,
  insideGitWorkTree,
  readAuthorityFile,
  readFileNoFollow,
  sameOpenedFile,
  type AuthorityFileInput,
  type NoFollowRead,
  type AuthorityFileRead,
  type AuthorityFileRefusal,
} from './authority-file.js';
