#!/usr/bin/env node
/**
 * Generated user docs (UDOC-08, UDOC-10). The reference pages come from the product itself, so
 * they cannot drift from it:
 *
 *   docs/cli.md               every command's help text, from the built `jevris` (UDOC-08)
 *   docs/platform-support.md  OS, architecture, Node range and per-harness certification status,
 *                             from assets/support-matrix.json and the certification records that
 *                             the release gates accept (UDOC-10)
 *
 *   node scripts/docs.mjs                          regenerate both (after npm run build)
 *   node scripts/docs.mjs platform --evidence <dir>
 *   node scripts/docs.mjs --check                  exit 1 when a page is out of date (release-check, CI)
 *
 * The CLI is run with a temporary HOME and a PATH of stub harness binaries, never the real ones.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { isMain } from './build.mjs';
import { testEnvironment, writeHarnessStubs } from './test.mjs';

const repoRoot = join(fileURLToPath(new URL('.', import.meta.url)), '..');
export const PAGES = { cli: 'docs/cli.md', platform: 'docs/platform-support.md' };
const OS_LABEL = { darwin: 'macOS', linux: 'Linux', win32: 'Windows' };
const GENERATED = '<!-- Generated by scripts/docs.mjs from the product. Do not edit by hand: run `npm run docs`. -->';

function sandbox(fn) {
  const dir = mkdtempSync(join(tmpdir(), 'jevris-docs-'));
  try {
    const home = join(dir, 'home');
    mkdirSync(join(home, '.config'), { recursive: true });
    const stubs = writeHarnessStubs(join(dir, 'bin'));
    return fn(testEnvironment(home, 'unused-real-home', stubs));
  } finally {
    rmSync(dir, { recursive: true, force: true, maxRetries: 3 });
  }
}

function jevris(args, env, root = repoRoot) {
  const result = spawnSync(process.execPath, [join(root, 'bin', 'jevris.mjs'), ...args], { cwd: root, env, encoding: 'utf8', shell: false, windowsHide: true, timeout: 60_000 });
  if (result.status !== 0) throw new Error(`jevris ${args.join(' ')} exited ${result.status}: ${result.stderr}`);
  return result.stdout.replace(/\r\n/g, '\n').trimEnd();
}

/**
 * Subcommands with their own, longer help text (`jevris help <command> <subcommand>`), each
 * given a section after its command's so the docs lint can check their flags.
 */
const SUBCOMMAND_SECTIONS = { data: ['delete'] };

/** Command names from the top-level help: the first word of each two-space-indented row. */
export function commandsFromHelp(help) {
  const names = [];
  for (const line of help.split('\n')) {
    const match = /^ {2}([a-z][a-z-]*(?: delete)?)(?:,| {2,})/.exec(line);
    if (match === null) continue;
    if (line.includes('Operator tools')) {
      for (const name of line.split(/ {3,}/)[0].trim().split(/,\s*/)) names.push(name);
    } else {
      names.push(match[1]);
      for (const sub of SUBCOMMAND_SECTIONS[match[1]] ?? []) names.push(`${match[1]} ${sub}`);
    }
  }
  return [...new Set(names)];
}

export function renderCli({ help, version, commands }) {
  const lines = [
    '# CLI reference',
    '',
    GENERATED,
    '',
    `This page is the help text of \`jevris\` ${version}, one section per command. Run \`jevris help <command>\` for the same text in a terminal.`,
    '',
    'Every command runs from the published package, with no clone and no build:',
    '',
    '```sh',
    'npx @cryptventure/jevris <command> [options]      # or, after npm i -g @cryptventure/jevris: jevris <command>',
    '```',
    '',
    '`--home` is optional everywhere: it defaults to `JEVRIS_HOME`, then to your home directory. Exit codes are the same for every command: `0` answered, `1` a negative answer (not found, not verified, an invalid plan, a failed gate), `2` a usage error or a refused request. Output is plain text; `--json` prints the result as JSON where a command supports it. Nothing is colour-only.',
    '',
    '## jevris --help',
    '',
    '```text',
    help,
    '```',
    '',
  ];
  for (const { name, text } of commands) lines.push(`## jevris ${name}`, '', '```text', text, '```', '');
  return `${lines.join('\n').trimEnd()}\n`;
}

export function collectCli(root = repoRoot) {
  return sandbox((env) => {
    const help = jevris(['--help'], env, root);
    const version = jevris(['--version'], env, root).replace(/^jevris\s+/, '');
    const commands = commandsFromHelp(help).map((name) => ({ name, text: jevris(['help', ...name.split(' ')], env, root) }));
    return { help, version, commands };
  });
}

/**
 * Per advertised harness and OS: the newest accepted certification record, or why none counts.
 * `records` are loaded evidence envelopes; `accepts(record)` is the gate evaluator's predicate.
 */
export function platformRows(matrix, records, accepts) {
  const rows = [];
  for (const entry of matrix.advertised) {
    for (const os of entry.os) {
      const candidates = records.filter((r) => r.kind === 'certification-record' && r.payload.harness === entry.harness && r.payload.operatingSystems.includes(os));
      const accepted = candidates.filter((r) => accepts(r) === null).sort((a, b) => String(b.payload.certifiedAt).localeCompare(String(a.payload.certifiedAt)));
      const best = accepted[0];
      rows.push(
        best === undefined
          ? { harness: entry.harness, os, status: 'not certified', detail: candidates.length === 0 ? 'no certification record' : `record not accepted: ${accepts(candidates[0])}` }
          : {
              harness: entry.harness,
              os,
              status: 'certified',
              detail: `harness ${best.payload.harnessVersionRange.minimum} to below ${best.payload.harnessVersionRange.maximumExclusive}; certified ${String(best.payload.certifiedAt).slice(0, 10)}, expires ${String(best.payload.expiresAt).slice(0, 10)}; features: ${best.payload.features.filter((f) => f.status === 'certified').map((f) => f.featureId).join(', ') || 'none'}`,
            },
      );
    }
  }
  return rows;
}

export function renderPlatform({ matrix, rows }) {
  const certified = rows.filter((r) => r.status === 'certified').length;
  const lines = [
    '# Platform support',
    '',
    GENERATED,
    '',
    'Jevris runs wherever Node.js runs the published package. What it may *do* inside a coding harness depends on a signed certification record for that harness, harness version range and operating system (SSOT §15.2, §15.4). Without one, Jevris observes and advises only: it never changes what the harness does.',
    '',
    '## Runtime',
    '',
    '| Requirement | Supported |',
    '| --- | --- |',
    `| Node.js | \`${matrix.node}\` |`,
    `| Architectures | ${matrix.architectures.join(', ')} |`,
    '| Operating systems | macOS, Linux, Windows |',
    '| Native modules | better-sqlite3 and @napi-rs/keyring ship prebuilt binaries for these; no compiler is needed |',
    '',
    '## Harness certification',
    '',
    `${certified} of ${rows.length} advertised combinations have an accepted certification record.`,
    '',
    '| Harness | OS | Status | Detail |',
    '| --- | --- | --- | --- |',
    ...rows.map((r) => `| ${r.harness} | ${OS_LABEL[r.os] ?? r.os} | ${r.status} | ${r.detail} |`),
    '',
    '"Not certified" means Jevris installs and observes in that harness, and `jevris doctor` reports the feature as unsupported or reduced. It does not route, add context or change a tool call there. Records are signed by the certification key in `assets/trust/release-keys.json` and expire; an expired record counts as none.',
    '',
  ];
  return `${lines.join('\n').trimEnd()}\n`;
}

export async function collectPlatform({ root = repoRoot, evidence = join(root, 'release-evidence'), nowMs = Date.now() } = {}) {
  const gates = await import(pathToFileURL(join(root, 'apps', 'cli', 'dist', 'gate-records.js')).href);
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const matrix = JSON.parse(readFileSync(join(root, 'assets', 'support-matrix.json'), 'utf8'));
  const trust = await gates.loadTrust(join(root, 'assets', 'trust', 'release-keys.json'));
  const loaded = existsSync(evidence) ? await gates.loadEvidence(evidence) : { accepted: [] };
  const records = loaded.accepted.map((entry) => entry.record);
  const ctx = { version: pkg.version, commit: null, nowMs, evidence: [], trust, matrix: [], packs: [] };
  return { matrix, rows: platformRows(matrix, records, (record) => gates.exclusionReason(record, ctx)) };
}

export const USAGE = [
  'Usage: node scripts/docs.mjs [cli] [platform] [--evidence <dir>] [--check]',
  '',
  'Regenerates docs/cli.md and docs/platform-support.md from the built product (npm run build first).',
  '  cli, platform     only these pages (default: both)',
  '  --evidence <dir>  the certification records for the platform page (default: release-evidence)',
  '  --check           change nothing; exit 1 when a page is out of date',
  '  -h, --help        print this and change nothing',
].join('\n');

/**
 * The command line: `{ help: true }`, `{ error }` for anything it does not know (nothing is
 * written then), or `{ check, evidence, pages }`.
 */
export function docsArgs(argv) {
  let check = false;
  let evidence;
  const pages = [];
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--help' || arg === '-h') return { help: true };
    if (arg === '--check') check = true;
    else if (arg === '--evidence') {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith('-')) return { error: '--evidence needs a directory' };
      evidence = value;
      i += 1;
    } else if (Object.hasOwn(PAGES, arg)) pages.push(arg);
    else return { error: `unknown argument: ${arg}` };
  }
  return { check, evidence, pages: pages.length > 0 ? [...new Set(pages)] : Object.keys(PAGES) };
}

async function main(argv) {
  const parsed = docsArgs(argv);
  if (parsed.help === true) {
    console.log(USAGE);
    return 0;
  }
  if (parsed.error !== undefined) {
    console.error(`docs: ${parsed.error}\n\n${USAGE}`);
    return 2;
  }
  const { check, evidence, pages } = parsed;
  let stale = 0;
  for (const page of pages) {
    const text = page === 'cli' ? renderCli(collectCli()) : renderPlatform(await collectPlatform(evidence === undefined ? {} : { evidence }));
    const path = join(repoRoot, PAGES[page]);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
    if (check) {
      if (current !== text) {
        stale += 1;
        console.error(`docs: ${PAGES[page]} is out of date; run npm run docs`);
      }
    } else if (current !== text) {
      writeFileSync(path, text);
      console.log(`docs: wrote ${PAGES[page]}`);
    }
  }
  return stale === 0 ? 0 : 1;
}

if (isMain(import.meta.url)) process.exit(await main(process.argv.slice(2)));
