#!/usr/bin/env node
/**
 * Generates the harness-facing files from their typed sources (TOOL-05, HKR-02), so no plugin
 * file is hand-edited:
 *
 * - plugins/shared/mcp.js: the MCP server (packages/mcp) bundled into one dependency-free
 *   file, with the tool output schemas embedded from the shared result contracts.
 * - plugins/claude/hooks/hooks.json: every Claude event the adapter maps, each running the
 *   hook launcher in exec form.
 * - plugins/shared/shim.js: domain F's one Kilo/OpenCode shim template, via its emitShims().
 *
 * The skills are not rendered here into any tree: plugins/shared/skills is the only committed
 * skill source, and the installer renders each harness's tree at install time with
 * apps/cli/src/skill-render.ts. This script checks that every source renders for every harness.
 * Nothing else is written into plugins/: the installer points each harness at the runtime
 * entries (dist/hook.mjs, plugins/shared/mcp.js).
 *
 * `--check` regenerates in memory and exits 1 when a committed file drifted.
 * This script does not spawn a harness and does not read the user's home.
 */
import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

/** Claude hook timeouts in seconds; the launcher's own deadline is far shorter. */
const CLAUDE_TIMEOUT_SECONDS = 5;
/** PreToolUse is registered only for the tools the worker-routing actuator may touch. */
const PRE_TOOL_MATCHERS = ['Agent', 'Task'];

const SCHEMA_DROP = new Set(['not', 'format', '$id', '$schema', '$comment']);

/** Client validators need plain JSON Schema: drop secret-pattern `not` clauses and formats. */
export function portableSchema(value) {
  if (Array.isArray(value)) return value.map(portableSchema);
  if (value === null || typeof value !== 'object') return value;
  const out = {};
  for (const key of Object.keys(value).sort()) {
    if (SCHEMA_DROP.has(key)) continue;
    out[key] = portableSchema(value[key]);
  }
  return out;
}

async function importDist(root, rel) {
  const full = join(root, rel);
  if (!existsSync(full)) throw new Error(`emit: ${rel} is missing; run tsc -b first`);
  return import(pathToFileURL(full).href);
}

export async function outputSchemas(root = repoRoot) {
  const contracts = await importDist(root, 'packages/contracts/dist/index.js');
  const schemas = {};
  for (const op of contracts.SURFACE_OPERATIONS) {
    schemas[op] = portableSchema(contracts.jsonSchemaOf(contracts.surfaceResultContract(op).schema));
  }
  return schemas;
}

function packageVersion(root) {
  return JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version;
}

/** The bundled MCP server text. Deterministic for the same sources. */
export async function renderMcp(root = repoRoot) {
  const entry = join(root, 'packages', 'mcp', 'dist', 'main.js');
  if (!existsSync(entry)) throw new Error('emit: packages/mcp/dist/main.js is missing; run tsc -b first');
  const esbuild = await import('esbuild');
  const schemas = await outputSchemas(root);
  const result = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    write: false,
    platform: 'node',
    format: 'esm',
    target: 'node22',
    legalComments: 'none',
    charset: 'utf8',
    define: {
      __JEVRIS_VERSION__: JSON.stringify(packageVersion(root)),
      __JEVRIS_OUTPUT_SCHEMAS__: JSON.stringify(schemas),
    },
    logLevel: 'silent',
  });
  const text = new TextDecoder().decode(result.outputFiles[0].contents);
  const header = '// Generated by scripts/emit-hook.mjs from packages/mcp. Do not edit.\n';
  return header + text;
}

/** The Claude plugin hooks.json: every mapped event runs the launcher in exec form. */
export async function renderClaudeHooks(root = repoRoot) {
  const claude = await importDist(root, 'packages/adapter-claude-code/dist/index.js');
  const handler = {
    type: 'command',
    command: 'node',
    args: ['${CLAUDE_PLUGIN_ROOT}/bin/hook.js', '--harness', claude.LAUNCHER_NAME],
    timeout: CLAUDE_TIMEOUT_SECONDS,
  };
  const hooks = {};
  for (const event of Object.keys(claude.CLAUDE_EVENTS)) {
    hooks[event] =
      event === 'PreToolUse'
        ? PRE_TOOL_MATCHERS.map((matcher) => ({ matcher, hooks: [handler] }))
        : [{ hooks: [handler] }];
  }
  return `${JSON.stringify({ hooks }, null, 2)}\n`;
}

function forbiddenText(rel, text) {
  if (text.includes('npx ') || text.includes('/Users/') || text.includes('/Volumes/') || text.includes('/home/runner/')) {
    throw new Error(`emit: ${rel} contains a machine path or npx`);
  }
}

/** Only node builtins may be imported by the standalone MCP server. */
export function nonBuiltinImports(text) {
  const found = [];
  const pattern = /(?:^|[\s;])(?:import|export)\s[^'"]*?from\s*['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]\s*\)/g;
  let match = pattern.exec(text);
  while (match !== null) {
    const spec = match[1] ?? match[2];
    if (spec !== undefined && !spec.startsWith('node:')) found.push(spec);
    match = pattern.exec(text);
  }
  return found;
}

function writeReal(root, rel, text) {
  const full = join(root, rel);
  mkdirSync(dirname(full), { recursive: true });
  if (existsSync(full) && lstatSync(full).isSymbolicLink()) rmSync(full);
  writeFileSync(full, text);
}

/**
 * Every shared skill source parses and renders for every harness with the installer's renderer
 * (SKL-01, SKL-02), each harness as its own manifest (plugins/<harness>/harness.json) declares.
 * Returns the rendered trees by harness folder; nothing is written.
 */
export async function checkSkills(root = repoRoot) {
  const render = await importDist(root, 'apps/cli/dist/skill-render.js');
  const entries = await render.readSkillSources(join(root, 'plugins', 'shared', 'skills'));
  if (entries.length === 0) throw new Error('emit: plugins/shared/skills has no skills');
  const trees = new Map();
  for (const harness of harnessDirs(root)) {
    const profile = await render.readSkillProfile(join(root, 'plugins', harness));
    const tree = render.renderSkillTree(entries, profile);
    for (const [rel, text] of tree) forbiddenText(`${harness} skills ${rel}`, text);
    trees.set(harness, tree);
  }
  if (trees.size === 0) throw new Error('emit: no plugins/<harness>/harness.json declares a harness');
  return trees;
}

/** The harness folders: every plugins/<name>/ with a harness.json (plugins/shared is the source). */
export function harnessDirs(root = repoRoot) {
  const plugins = join(root, 'plugins');
  return readdirSync(plugins)
    .filter((name) => name !== 'shared' && existsSync(join(plugins, name, 'harness.json')))
    .sort();
}

/** The generated files, by repository path. */
export async function renderAll(root = repoRoot) {
  const mcp = await renderMcp(root);
  const imports = nonBuiltinImports(mcp);
  if (imports.length > 0) throw new Error(`emit: mcp.js imports ${imports.join(', ')}`);
  forbiddenText('plugins/shared/mcp.js', mcp);
  const hooks = await renderClaudeHooks(root);
  forbiddenText('plugins/claude/hooks/hooks.json', hooks);
  const files = new Map([
    ['plugins/shared/mcp.js', mcp],
    ['plugins/claude/hooks/hooks.json', hooks],
  ]);
  await checkSkills(root);
  return files;
}

async function shimEmitter(root) {
  const script = join(root, 'packages', 'adapter-kilocode', 'scripts', 'emit-shim.mjs');
  if (!existsSync(script)) return null;
  const mod = await import(pathToFileURL(script).href);
  return typeof mod.emitShims === 'function' ? mod.emitShims : null;
}

export async function emit({ root = repoRoot, check = false } = {}) {
  const files = await renderAll(root);
  const drift = [];
  for (const [rel, text] of files) {
    const full = join(root, rel);
    const current = existsSync(full) ? readFileSync(full, 'utf8') : null;
    if (current === text) continue;
    if (check) drift.push(rel);
    else writeReal(root, rel, text);
  }
  const emitShims = await shimEmitter(root);
  if (emitShims !== null) {
    const shimDrift = await emitShims({ root, check });
    if (check && Array.isArray(shimDrift)) drift.push(...shimDrift);
  }
  // Earlier builds wrote the Claude plugin's own bin/ copies; the installer now points at the
  // runtime entries, so a leftover folder is removed.
  if (!check) rmSync(join(root, 'plugins', 'claude', 'bin'), { recursive: true, force: true });
  return { drift };
}

function isMain() {
  const entry = process.argv[1];
  return typeof entry === 'string' && pathToFileURL(entry).href === import.meta.url;
}

if (isMain()) {
  const check = process.argv.includes('--check');
  try {
    const { drift } = await emit({ check });
    if (drift.length > 0) {
      console.error(`emit: generated files are out of date: ${drift.join(', ')}. Run node scripts/emit-hook.mjs.`);
      process.exit(1);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
}
