#!/usr/bin/env node
/**
 * Generates the one Kilo and OpenCode plugin template, plugins/shared/shim.js, from the built
 * adapters (HKR-02, KIL-01, OPC-01, decision D-F4). The installer renders it into either
 * harness's plugin file with renderShimPlugin (packages/adapter-kilocode/src/shim-template.ts);
 * no per-harness copy is tracked.
 *
 * A rendered plugin is one self-contained ES module: the adapter's zero-import core and
 * protocol, inlined, plus a hook table built with createHooks(spawnForwarder(...)). It carries
 * the single install-time line `const JEVRIS_RUNTIME = null;`. While that line is null the
 * plugin registers no hooks at all (inert). The installer replaces it with
 * `const JEVRIS_RUNTIME = {"node":"node","launcher":"<abs hook launcher>"};`.
 *
 * The template is written only when rendering it for each harness gives exactly what that
 * harness's own adapter produces, so the two adapters cannot drift apart silently.
 *
 *   node packages/adapter-kilocode/scripts/emit-shim.mjs          # write the template
 *   node packages/adapter-kilocode/scripts/emit-shim.mjs --check  # exit 1 on drift
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

export const RUNTIME_LINE = 'const JEVRIS_RUNTIME = null;';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

export const TEMPLATE_OUT = ['plugins', 'shared', 'shim.js'];

export const SHIMS = [
  { harness: 'kilocode', adapter: 'adapter-kilocode' },
  { harness: 'opencode', adapter: 'adapter-opencode' },
];

/** A harness's shim values from its manifest, plugins/<harness>/harness.json. */
export function shimTarget(spec, root = repoRoot) {
  const manifest = JSON.parse(readFileSync(join(root, 'plugins', spec.harness, 'harness.json'), 'utf8'));
  return { harness: manifest.harness, launcher: manifest.launcher, exportForm: manifest.plugin.export };
}

async function templateModule(root) {
  return import(pathToFileURL(join(root, 'packages', 'adapter-kilocode', 'dist', 'shim-template.js')).href);
}

/** Removes `import ... from './x.js';` lines and `export` keywords from compiled adapter code. */
export function inlineModule(text) {
  const lines = [];
  for (const line of text.split('\n')) {
    if (/^import\s[^;]*from\s+'\.\/[\w.-]+\.js';\s*$/.test(line)) continue;
    if (/^export\s*\{[^}]*\}\s*(?:from\s+'[^']+')?;\s*$/.test(line)) continue;
    if (/^export \* from /.test(line)) continue;
    if (/^\/\/# sourceMappingURL=/.test(line)) continue;
    lines.push(line.replace(/^export (async function|function|const|let|class) /, '$1 '));
  }
  return lines.join('\n').trimEnd();
}

/** One harness's plugin, straight from its own adapter; `exportLine` is its loader's export. */
export function renderShim(spec, exportLine, root = repoRoot) {
  const dist = join(root, 'packages', spec.adapter, 'dist');
  const common = inlineModule(readFileSync(join(dist, 'common.js'), 'utf8'));
  // Recorded fixtures are test data; the shim ships everything before them.
  const protocolText = readFileSync(join(dist, 'protocol.js'), 'utf8');
  const cut = protocolText.search(/^export const FIXTURES = /m);
  const protocol = inlineModule(cut === -1 ? protocolText : protocolText.slice(0, cut));
  if (/^\s*(?:import|export)\s/m.test(`${common}\n${protocol}`)) {
    throw new Error(`${spec.adapter}: an import or export survived inlining`);
  }
  return [
    '// Jevris plugin for Kilo and OpenCode. GENERATED by packages/adapter-kilocode/scripts/emit-shim.mjs',
    '// from the Jevris harness adapters; do not edit. Hooks forward bounded native events to the Jevris hook',
    '// launcher and never make a permission decision. The compaction hook waits (at most 1.5 s) to',
    '// append context lines; a turn and a task call wait at most 300 ms, for text to show and for a',
    '// certified route, which writes a model and nothing else. The native permission flow stays',
    '// authoritative. The installer replaces the next line with the absolute runtime paths;',
    '// while it is null the plugin registers no hooks.',
    RUNTIME_LINE,
    '',
    common,
    '',
    protocol,
    '',
    'function jevrisRuntime(value) {',
    "  if (value === null || typeof value !== 'object') return null;",
    '  const { node, launcher } = value;',
    "  if (typeof node !== 'string' || node.length === 0 || typeof launcher !== 'string' || launcher.length === 0) return null;",
    '  return { node, launcher };',
    '}',
    '',
    '// The harness passes its PluginInput; `directory` and `worktree` bound the project config check.',
    'const server = async (input) => {',
    '  const runtime = jevrisRuntime(JEVRIS_RUNTIME);',
    '  if (runtime === null) return {};',
    "  const roots = input !== null && typeof input === 'object' ? { directory: input.directory, worktree: input.worktree } : { directory: undefined, worktree: undefined };",
    '  return createHooks(spawnForwarder(runtime.node, runtime.launcher, LAUNCHER_NAME), undefined, projectConfigGuard(HARNESS_ID, roots, nodeConfigHost));',
    '};',
    '',
    exportLine,
    '',
  ].join('\n');
}

/**
 * The template: the Kilo plugin with its three harness lines turned into placeholders. Throws
 * unless rendering it back gives each harness's own adapter output byte for byte.
 */
export async function renderTemplate(root = repoRoot) {
  const { SHIM_EXPORTS, SHIM_PLACEHOLDERS, renderShimPlugin } = await templateModule(root);
  const [first] = SHIMS;
  const firstTarget = shimTarget(first, root);
  const lines = renderShim(first, SHIM_PLACEHOLDERS.exports, root).split('\n');
  const swap = (from, to) => {
    const at = lines.flatMap((line, index) => (line === from ? [index] : []));
    if (at.length !== 1) throw new Error(`emit-shim: ${first.adapter} has ${at.length} lines "${from}"`);
    lines[at[0]] = to;
  };
  swap(`const HARNESS_ID = '${first.harness}';`, SHIM_PLACEHOLDERS.harness);
  swap(`const LAUNCHER_NAME = '${firstTarget.launcher}';`, SHIM_PLACEHOLDERS.launcher);
  const template = lines.join('\n');
  for (const spec of SHIMS) {
    const target = shimTarget(spec, root);
    const direct = renderShim(spec, SHIM_EXPORTS[target.exportForm], root);
    if (renderShimPlugin(template, target) !== direct) {
      throw new Error(`emit-shim: the shared template does not render ${spec.adapter}'s plugin; the adapters differ beyond the harness lines`);
    }
  }
  return template;
}

/** Replaces the runtime line of a shim. Refuses unless exactly one line matches. */
export function substituteRuntime(text, runtime) {
  const lines = text.split('\n');
  const at = lines.flatMap((line, index) => (line === RUNTIME_LINE ? [index] : []));
  if (at.length !== 1) return null;
  const value = JSON.stringify({ node: runtime.node, launcher: runtime.launcher });
  lines[at[0]] = `const JEVRIS_RUNTIME = ${value};`;
  return lines.join('\n');
}

export async function emitShims({ root = repoRoot, check = false } = {}) {
  const text = await renderTemplate(root);
  const out = join(root, ...TEMPLATE_OUT);
  let current = null;
  try {
    current = readFileSync(out, 'utf8');
  } catch {
    current = null;
  }
  if (current === text) return [];
  if (check) return [TEMPLATE_OUT.join('/')];
  writeFileSync(out, text);
  return [];
}

if (process.argv[1] !== undefined && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  const drift = await emitShims({ check });
  if (drift.length > 0) {
    process.stderr.write(`shim drift: ${drift.join(', ')}. Run node packages/adapter-kilocode/scripts/emit-shim.mjs\n`);
    process.exit(1);
  }
}
