/** `jevris pack` help, kept apart so help loads without the pack runtime (PAK-01..08). */
export const PACK_HELP = [
  'Usage: jevris pack <subcommand> [--home <dir>] [--json]',
  '',
  'Packs add declarative decisions, evidence selectors and rules to Jevris. Installing one never',
  'activates it: a pack moves through draft, fixture-tested, shadow-approved, canary and stable,',
  'and only your approval of its delta hash activates it.',
  '',
  'Subcommands:',
  '  list                                   installed packs, their stage, active version and workspaces',
  '  inspect <dir | id@version>             validate a pack; show its signature, delta and conflicts',
  '  install <dir>                          copy a pack in as a draft and print its delta hash',
  '  test <id@version>                      run its fixtures; a pass makes it fixture-tested',
  '  shadow <id@version> --report <file>    attach a shadow report (jevris shadow --out); shadow-approved',
  '  approve <delta-hash>                   approve that delta: the version becomes the active canary',
  '  canary <id> --metrics <file> [--kill-switch]   record canary metrics; a regression rolls back',
  '  promote <id>                           canary to stable after passing canary metrics',
  '  rollback <id>                          restore the previous version and its data backup',
  '  enable <id> --workspace <dir>          use an active pack in one workspace',
  '  disable <id> --workspace <dir>         stop using it there',
  '  uninstall <id> [--cleanup [--yes]]     remove its versions and workspace enablements; data kept',
  '  publisher list | add <id> --key <pem> --key-id <id> | remove <id>',
  '',
  'approve and publisher add widen what Jevris may run and send, so they need a person at an',
  'interactive terminal who answers y: --yes, --json, a pipe or a script is refused',
  '(CHANNEL_REFUSED) and nothing changes.',
  '',
  'Options:',
  '  --home <dir>         Jevris home (default: JEVRIS_HOME, else your home directory)',
  '  --report <file>      shadow: the shadow report to attach',
  '  --metrics <file>     canary: the canary metrics (packId, version, tasks, verifiedSuccessRate,',
  '                       baselineVerifiedSuccessRate, privacyViolations)',
  '  --kill-switch        canary: also activate the kill switch on any regression',
  '  --workspace <dir>    enable, disable: the workspace',
  '  --cleanup            uninstall: also delete the pack data and backups (asks, or --yes)',
  '  --key <pem>          publisher add: the Ed25519 public key file',
  '  --key-id <id>        publisher add: the key id the pack signatures name',
  '  --yes                uninstall --cleanup: confirm without a prompt',
  '  --json               one JSON document',
  '',
  'Exit codes: 0 done; 1 a check failed (fixtures failed, canary regression); 2 usage error or',
  'refused (the reason code is printed).',
  '',
  'Examples:',
  '  jevris pack install ./my-pack',
  '  jevris pack test jevris.routing@0.1.0',
  '  jevris pack approve sha256:...',
].join('\n');
